schema_version: 1

context:
  name: gregor
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gregor-${{ version }}.tar.gz
  sha256: e061b9449b3bbca430b5ed1ddb41f2cec966961f75ddc7d1e2aef61658a42c99

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gregor = gregor.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=46.1.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=1.2
    - numpy
    - matplotlib-base
    - geopandas
    - xarray
    - rasterio
    - rioxarray
    - rasterstats
    - click

tests:
  - python:
      imports:
        - gregor
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true
  - script:
     - gregor --help

about:
  summary: A library for spatial aggregation and disaggregation
  license: MIT
  license_file: LICENSE.txt
  homepage: https://gregor.readthedocs.io

extra:
  recipe-maintainers:
    - jnnr
